#!/usr/bin/env python3
"""Build the static site.

Each page in src/pages/*.html is wrapped in src/partials/layout.html and
written to the repository root (src/pages/rooms.html -> rooms.html).

Page files start with a metadata comment:

    <!--
    title: Rooms & Suites
    description: One-sentence summary for search results.
    -->

Inside any page or partial:
    <!-- @include name -->   inserts src/partials/name.html
    {{ key }}                inserts a metadata value (title, description, page, ...)

Usage:
    python3 tools/build.py          build all pages
    python3 tools/build.py --check  exit 1 if the committed pages are out of date
"""
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
META_RE = re.compile(r"\A\s*<!--(.*?)-->\s*", re.S)
INCLUDE_RE = re.compile(r"<!--\s*@include\s+([\w-]+)\s*-->")
VAR_RE = re.compile(r"\{\{\s*([\w-]+)\s*\}\}")
NAV_RE = re.compile(r'data-nav="([\w-]+)"')

PARTIALS = {p.stem: p.read_text(encoding="utf-8") for p in (SRC / "partials").glob("*.html")}

# Fingerprint of the stylesheet and script, appended to their URLs (?v=...) so a
# new deploy is never mixed with old copies cached by browsers.
ASSET_VERSION = hashlib.sha1(
    b"".join((ROOT / f).read_bytes() for f in ("assets/css/style.css", "assets/js/main.js"))
).hexdigest()[:10]


def expand_includes(text, depth=0):
    if depth > 8:
        raise RuntimeError("Include nesting too deep")
    if not INCLUDE_RE.search(text):
        return text
    return expand_includes(INCLUDE_RE.sub(lambda m: PARTIALS[m.group(1)], text), depth + 1)


def render_vars(text, ctx, source):
    def sub(m):
        key = m.group(1)
        if key not in ctx:
            raise KeyError(f"{source}: unknown variable {{{{ {key} }}}}")
        return ctx[key]
    return VAR_RE.sub(sub, text)


def parse_page(path):
    raw = path.read_text(encoding="utf-8")
    meta = {}
    m = META_RE.match(raw)
    if m:
        for line in m.group(1).strip().splitlines():
            if ":" in line:
                key, value = line.split(":", 1)
                meta[key.strip()] = value.strip()
        raw = raw[m.end():]
    for required in ("title", "description"):
        if required not in meta:
            raise KeyError(f"{path.name}: missing '{required}' in the metadata comment")
    return meta, raw


def build_page(path):
    meta, body = parse_page(path)
    page = path.stem
    ctx = {
        "page": page,
        "nav": meta.get("nav", page),
        "body_class": meta.get("body_class", ""),
        "og_image": meta.get("og_image", "assets/img/real/palace.jpg"),
        "asset_version": ASSET_VERSION,
        **meta,
    }
    ctx["full_title"] = ctx["title"] if page == "index" else f"{ctx['title']} — The Pharo, Nittambuwa"

    layout = expand_includes(PARTIALS["layout"])
    layout = render_vars(layout, ctx, "layout")
    content = render_vars(expand_includes(body), ctx, path.name)
    html = layout.replace("<!-- @content -->", content.strip())

    # Mark the current section in every navigation menu.
    html = NAV_RE.sub(
        lambda m: f'data-nav="{m.group(1)}"' + (' aria-current="page"' if m.group(1) == ctx["nav"] else ""),
        html,
    )
    banner = f"<!-- Generated by tools/build.py from src/pages/{path.name}. Edit that file, then run: python3 tools/build.py -->\n"
    return html.replace("<!doctype html>\n", "<!doctype html>\n" + banner, 1)


def check_links(pages, outputs):
    """Warn about links to local pages that don't exist."""
    known = {p.stem + ".html" for p in pages} | {"404.html"}
    problems = []
    for name, html in outputs.items():
        for href in re.findall(r'href="([\w-]+\.html)(?:#[\w-]*)?"', html):
            if href not in known:
                problems.append(f"{name}: link to missing page {href}")
    return problems


def main():
    check = "--check" in sys.argv
    pages = sorted((SRC / "pages").glob("*.html"))
    outputs = {p.name: build_page(p) for p in pages}

    problems = check_links(pages, outputs)
    for p in problems:
        print("warning:", p)

    stale = []
    for name, html in outputs.items():
        target = ROOT / name
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != html:
                stale.append(name)
        else:
            target.write_text(html, encoding="utf-8")
    if check and stale:
        print("Out of date (run python3 tools/build.py):", ", ".join(stale))
        return 1
    print(("Checked " if check else "Built ") + ", ".join(outputs))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
